//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _99X_CBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CBS_Employees
    {
        public string Employee_Name { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> Date_Joined { get; set; }
        public string Career_Started_On { get; set; }
        public string Appraisal_Score { get; set; }
        public string EmpID { get; set; }
        public int ID { get; set; }
    }
}
