//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _99X_CBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CBS_UniversitySessions
    {
        public string Employee_Name { get; set; }
        public Nullable<System.DateTime> Session_Date { get; set; }
        public string Initiated_By { get; set; }
        public string Location { get; set; }
        public string Number_Of_Participants { get; set; }
        public string Participants { get; set; }
        public string Session_Type { get; set; }
        public string Time_Duration { get; set; }
        public string Topic { get; set; }
        public string To_the_University { get; set; }
        public string EmpID { get; set; }
        public bool Approved { get; set; }
        public string EditedBy { get; set; }
        public int TargetRowID { get; set; }
        public int ID { get; set; }
    }
}
