//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _99X_CBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CBS_Travels
    {
        public string Employee_Name { get; set; }
        public Nullable<System.DateTime> Started_Date { get; set; }
        public string Number_Of_Days { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Allowance_In_SLR { get; set; }
        public string Purpose { get; set; }
        public string EmpID { get; set; }
        public int ID { get; set; }
    }
}
