//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _99X_CBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CBS_MentorBuddy
    {
        public string Employee_Name { get; set; }
        public string Mentor_or_Buddy_Type { get; set; }
        public string Mentor_or_Buddy { get; set; }
        public int ID { get; set; }
    }
}
