//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _99X_CBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CBS_Increments
    {
        public string Employee_Name { get; set; }
        public string Effective_Date { get; set; }
        public string Increment_Amount { get; set; }
        public int ID { get; set; }
    }
}
