//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _99X_CBS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CBS_Attendances
    {
        public string Employee_Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Average_InTime { get; set; }
        public string Average_OutTime { get; set; }
        public string Weekends_Worked { get; set; }
        public string Medical_Leaves_Taken { get; set; }
        public string Casual_Leaves_Taken { get; set; }
        public string Annual_Leaves_Taken { get; set; }
        public string Lieu_Leaves_Taken { get; set; }
        public string Number_of_Days_Reported_to_Work { get; set; }
        public string EmpID { get; set; }
        public bool Approved { get; set; }
        public string  EditedBy { get; set; }
        public Nullable<int> TargetRowID { get; set; }
        public int ID { get; set; }
    }
}
