//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _99X_CBS.Models
{
	using System;
	using System.Collections.Generic;

	public partial class CBS_Trainings
	{
		public string Employee_Name { get; set; }
		public int Year { get; set; }
		public string Course_Name { get; set; }
		public string Training_Provider { get; set; }
		public string Training_Type { get; set; }
		public string Category { get; set; }
		public string Training_Month { get; set; }
		public string Time_Duration { get; set; }
		public string Investment { get; set; }
		public string EmpID { get; set; }
		public string Training_Focus { get; set; }
		public string ForeignOrLocal { get; set; }
		public bool Approved { get; set; }
		public string EditedBy { get; set; }
		public Nullable<int> TargetRowID { get; set; }
		public int ID { get; set; }
	}
}
